### PR TITLE
[WIP] Make crate #![no_std]

### LINKED ISSUE #7: Support #![no_std]
libdiffuzz doesn't make much use of the standard library. It can probably be switched to the corresponding libcore primitives and compiled in #![no_std] mode. 

Among other things, this will reduce the size of the generated binary and may allow cross-compilation to the more obscure architectures.

### PR DESCRIPTION
**Pull request by jhwgh1968**
Closes #7.

### CODE REVIEW

**Comment by Shnatsel** [comment]
Sorry it took me so long to get around to reviewing this. Looks good to me, I'll merge it once I run some basic tests.

Do you have any use cases for `#[no_std]` configuration of libdiffuzz? I'd like to better understand what the requirements for this configuration are.

**Comment by jhwgh1968** [comment]
Someday I hope to run it in on [smoltcp](https://github.com/m-labs/smoltcp) in an embedded device configuration. But the key word is "someday".

If you accept unsolicited e-mails to your GitHub profile address, I can talk more and perhaps ask a couple random questions as well.

**Comment by Shnatsel** [comment]
I do, that's why it's specified there in the first place. You can also catch me on Rust zulip: https://rust-lang.zulipchat.com/, same username as here.

**Comment by Shnatsel** [comment]
I have verified that the std mode works as expected. However, I could not get the no_std mode to compile. Since there are no features to toggle it in `Cargo.toml`, I've tried `env RUSTFLAGS='--cfg=no_std' cargo build --release` but that didn't work, here's the error:

```
> env RUSTFLAGS='--cfg=no_std' cargo build --release
   Compiling rand_core v0.2.1
   Compiling libc v0.2.43
   Compiling rand v0.5.5
   Compiling diffuzz v0.1.0 (/home/shnatsel/Code/libdiffuzz)
error[E0432]: unresolved import `std`
  --> src/lib.rs:22:13
   |
22 |         use std::env;
   |             ^^^ maybe a missing `extern crate std;`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `diffuzz`.

To learn more, run the command again with --verbose.
```

I'd wager a guess that putting `use` statements under `if !cfg!(no_std)` is what triggers the error, because unlike `#[cfg()]` attributes that are resolved before compilation, `cfg!` merely returns a constant result but does not eliminate the code under the if.

Any ideas on how to resolve this properly?

**Comment by jhwgh1968** [comment]
> Any ideas on how to resolve this properly?

With a rewrite like I did. :laughing: 

It's quite a bit uglier, but I believe this should work.

NB: no_std mode won't check, because it requires the user to define an allocator and a panic handler.

**Comment by Shnatsel** [comment]
I believe people are standardizing around feature called `std`, see for example https://github.com/rust-num/num-integer/issues/4

We do not need a panic handler because `panic=abort` is the most appropriate behaviour.

Also, it has just occurred to me that supporting a `no_std` mode in libdiffuzz is not sufficient to make it usable in embedded devices. The injection approach for it depends on having a dynamic linker, which embedded devices do not have. So AFAIK all we would gain from no_std mode in current libdiffuzz is a smaller binary size in exchange for absence of some features. That alone does not seem to be worth the effort.

AFAIK in order to support embedded we'd have to provide an allocator through the Rust allocator API instead of overriding libc functions. Sadly I know nothing about embedded allocators, I don't even know if they handle stack-based (e.g. array) or heap-based (e.g. vector) allocations, so I'm afraid I will not be of much help here.

Frankly my plan for `no_std` has been "wait until someone with a clear embedded use case shows up", otherwise there's no real way to gauge if what we're doing is useful or not. Given that you don't seem to be auditing an embedded system right now, I'd suggest to shelve the no_std mode for libdiffuzz until we meet someone who does.

**Comment by jhwgh1968** [comment]
In that case, I will close this for now. Hopefully it will at least provide a template if someone needs that use case.

**Pull request closed without merging**
